PHPチャレンジ課題1
kikucmy/furiPHP_exercise pull request #6
Opened 2021-03-23 12:50 UTC by kikucmy

### カリキュラムURL
https://github.com/elites-team/2months_course/blob/master/doc/06_php/exercise/06.md

### メッセージ
チャレンジ課題1を作成しました。  
確認お願いいたします！

2021-03-23 22:43 UTC, kazu-taka requested changes
@kikucmy 
ほぼ完璧です✨
またしても解答にほぼ近いコードで焦りました笑
一部修正お願いします🙏

2021-03-23 22:43 UTC, kazu-taka commented on challenge1_3.php
> +    echo $all_team[2] . "\n";
@kikucmy 
これでも問題ないですが、万が一`$team_a`や`$team_b`に要素が追加になった場合、コードを修正しないといけないので、要素が増えたり減ったりしてもコードを修正しなくてもいいように変更お願いします😊

2021-03-23 22:43 UTC, kazu-taka commented on challenge1_func.php
> +    $val = array_rand(range(100, 500), 1);
@kikucmy 
`range`を使用して配列を作ってから、ランダムに取り出しても問題ないですが、[`rand`](https://www.php.net/manual/ja/function.rand.php)関数だと1発でランダムな値を生成できるのでおすすめです✨

2021-03-23 22:43 UTC, kazu-taka commented on challenge1_5.php
> +        $attack_point = array_rand(range(500, 3000), 1);
@kikucmy 
こちらも[`rand`](https://www.php.net/manual/ja/function.rand.php)関数がおすすめです✨

2021-03-24 05:13 UTC, kikucmy commented on challenge1_3.php
> +    echo $all_team[2] . "\n";
修正しましたので、確認お願いします！
$all_teamをforeachで参照・取得するように修正したのですが、
カリキュラムの「ただし、foreachで参照するのは$all_teamsのみ」に
そぐわなかったら再度修正しますので、ご指摘下さい🙏

2021-03-24 05:17 UTC, kikucmy commented on challenge1_func.php
> +    $val = array_rand(range(100, 500), 1);
array_rand関数は見つけられたのですが、rand関数まではたどり着きませんでした！
ありがとうございます😊

2021-03-24 05:27 UTC, kazu-taka commented on challenge1_3.php
> +    echo $all_team[2] . "\n";
@kikucmy 
最初の解答が正しかったです！！！！！！！
私のミスです(T_T)
すみません！！

2021-03-24 05:28 UTC, kazu-taka commented
@kikucmy 
マージしてOKです😊
![LGTM](https://image.lgtmoon.dev/73573)

2021-03-24 05:36 UTC, merged